// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvCDg5kXYDLKw4RNKJ3iNN86jW_TBPR2k',
    appId: '1:934299431567:web:c7a50ef617cf91c89336fa',
    messagingSenderId: '934299431567',
    projectId: 'app-medhavi',
    authDomain: 'app-medhavi.firebaseapp.com',
    storageBucket: 'app-medhavi.firebasestorage.app',
    measurementId: 'G-Z0PF2SCPT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANxHmNx5Ovr8hJA3rhqqzElA-a2_L6jYM',
    appId: '1:934299431567:android:4d1fcc900879c6ab9336fa',
    messagingSenderId: '934299431567',
    projectId: 'app-medhavi',
    storageBucket: 'app-medhavi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0oPhzNKsrEkmA_VDWEfKuqK08zRrOz7g',
    appId: '1:934299431567:ios:3dff6e2cec6cf5769336fa',
    messagingSenderId: '934299431567',
    projectId: 'app-medhavi',
    storageBucket: 'app-medhavi.firebasestorage.app',
    iosBundleId: 'com.example.medhavi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0oPhzNKsrEkmA_VDWEfKuqK08zRrOz7g',
    appId: '1:934299431567:ios:3dff6e2cec6cf5769336fa',
    messagingSenderId: '934299431567',
    projectId: 'app-medhavi',
    storageBucket: 'app-medhavi.firebasestorage.app',
    iosBundleId: 'com.example.medhavi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvCDg5kXYDLKw4RNKJ3iNN86jW_TBPR2k',
    appId: '1:934299431567:web:166a776b577ecbea9336fa',
    messagingSenderId: '934299431567',
    projectId: 'app-medhavi',
    authDomain: 'app-medhavi.firebaseapp.com',
    storageBucket: 'app-medhavi.firebasestorage.app',
    measurementId: 'G-CQPPTM77F1',
  );
}
